# .moco.toml
base_dir = "runs"
summary_file = "summary.md"

[run]
force = false
cleanup_on_fail = false
no_pushd = false
stdout_file = "stdout.log"
stderr_file = "stderr.log"

[status]
level = "normal"
format = "text"

[archive]
format = "tar.gz"
destination = "archives"
